# Generated by Django 5.0.6 on 2024-05-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='password',
        ),
    ]
